<a href="https://colab.research.google.com/github/gg5d/DS-3005/blob/main/hw_02_firstname_lastname.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import numpy.linalg as npl
import pandas as pd
from IPython.core.interactiveshell import InteractiveShell
import sympy as sym

In [ ]:
InteractiveShell.ast_node_interactivity = "all"

## 2.2 Matrices

### How to write Matrices in Python - EXPAND

numpy vstack, hstack, matrix, array


sympy matrix

In [ ]:
A = np.matrix([[1,2,3],[3,2,1]])
B = np.matrix([[0,2],[1,-1],[0,1]])
print(f"A\n {A}")
print(f"B\n {B}\n")
C = sym.Matrix(A)
C

A
 [[1 2 3]
 [3 2 1]]
B
 [[ 0  2]
 [ 1 -1]
 [ 0  1]]



Matrix([
[1, 2, 3],
[3, 2, 1]])

### Matrix multiplication
numpy dot()
@ operator

In [ ]:
AB = np.dot(A,B)
print(AB)

[[2 3]
 [2 5]]


In [ ]:
BA = np.dot(B,A)
print(BA)

[[ 6  4  2]
 [-2  0  2]
 [ 3  2  1]]


In [ ]:
A.transpose()

matrix([[1, 3],
        [2, 2],
        [3, 1]])

#### Figure 2.5
*Even if both matrix multiplications $AB$ and $BA$ are defined, the dimensions of the results can be different.*

In [ ]:
B@A

matrix([[ 6,  4,  2],
        [-2,  0,  2],
        [ 3,  2,  1]])

In [ ]:
A@B #as seen above

matrix([[2, 3],
        [2, 5]])

### Example 2.6
Elementary operations are key to solving systems of linear equations and involve the following.
1. Exchange of two equations, or rows in the matrix.
2. Multiplication of an equation, or row, with a constant $\lambda \in \mathbb{R}$.
3. Addition of two equation, or rows.

In [ ]:
a = sym.Symbol('a')
A = np.vstack([[-2,4,-2,-1,4],[4,-8,3,-3,1],[1,-2,1,-1,1],[1,-2,0,-3,4]])
A = sym.Matrix(A)
b = np.vstack([-3,2,0,a])
b = sym.Matrix(b)
Ab = np.hstack([A,b])
Ab = sym.Matrix(Ab)

Ab

Matrix([
[-2,  4, -2, -1, 4, -3],
[ 4, -8,  3, -3, 1,  2],
[ 1, -2,  1, -1, 1,  0],
[ 1, -2,  0, -3, 4,  a]])

In [ ]:
Ab.row_swap(0,2) # Swap row 1 and 3.
Ab

Matrix([
[ 1, -2,  1, -1, 1,  0],
[ 4, -8,  3, -3, 1,  2],
[-2,  4, -2, -1, 4, -3],
[ 1, -2,  0, -3, 4,  a]])

In [ ]:
Ab[3,:] = -1*Ab[0,:]+Ab[3,:] # Addition of two equation, or rows. Subtract row 1 from 4.
Ab

Matrix([
[ 1, -2,  1, -1, 1,  0],
[ 4, -8,  3, -3, 1,  2],
[-2,  4, -2, -1, 4, -3],
[ 0,  0, -1, -2, 3,  a]])

In [ ]:
Ab[2,:] = 2*Ab[0,:] + Ab[2,:]  # Addition of two equation, or rows. Add 2 * row 1 to row 3.
Ab

Matrix([
[1, -2,  1, -1, 1,  0],
[4, -8,  3, -3, 1,  2],
[0,  0,  0, -3, 6, -3],
[0,  0, -1, -2, 3,  a]])

In [ ]:
Ab[1,:] = -4*Ab[0,:] + Ab[1,:] # Addition of two equation, or rows. Subtract 4 * row 1 to row 2
Ab

Matrix([
[1, -2,  1, -1,  1,  0],
[0,  0, -1,  1, -3,  2],
[0,  0,  0, -3,  6, -3],
[0,  0, -1, -2,  3,  a]])

In [ ]:
Ab[3,:] = -Ab[1,:] +Ab[3,:]# Addition of two equation, or rows. Add -Row 2 to Row 4
Ab

Matrix([
[1, -2,  1, -1,  1,     0],
[0,  0, -1,  1, -3,     2],
[0,  0,  0, -3,  6,    -3],
[0,  0,  0, -3,  6, a - 2]])

In [ ]:
Ab[3,:] = -Ab[2,:] + Ab[3,:]
Ab

Matrix([
[1, -2,  1, -1,  1,     0],
[0,  0, -1,  1, -3,     2],
[0,  0,  0, -3,  6,    -3],
[0,  0,  0,  0,  0, a + 1]])

In [ ]:
Ab[1,:] = -1*Ab[1,:] # Multiplication of an equation, or row, with a constant. Invert row 2
# Ab = Ab.astype(float)
Ab

Matrix([
[1, -2, 1, -1, 1,     0],
[0,  0, 1, -1, 3,    -2],
[0,  0, 0, -3, 6,    -3],
[0,  0, 0,  0, 0, a + 1]])

In [ ]:
Ab[2,:] = -1/3*Ab[2,:] # Multiplication of an equation, or row, with a constant. Divide row 3 by -3
Ab

Matrix([
[1, -2, 1,  -1,    1,     0],
[0,  0, 1,  -1,    3,    -2],
[0,  0, 0, 1.0, -2.0,   1.0],
[0,  0, 0,   0,    0, a + 1]])

Clearly $ a+1=0$, that is the solution exists only if $a=-1$.

In [ ]:
sym.solveset(sym.Eq(a+1,0), a)  # solve lin eq with sympy

{-1}

In [ ]:
Ab[3,5] = 0
Ab

Matrix([
[1, -2, 0,   0,   -2,   2],
[0,  0, 1,  -1,    3,  -2],
[0,  0, 0, 1.0, -2.0, 1.0],
[0,  0, 0,   0,    0,   0]])

We keep doing Gaussian Elimination until we get Reduced Row Echelon form



In [ ]:
Ab[0,:] = Ab[0,:] + -1*Ab[1,:]
Ab

Matrix([
[1, -2, 0,   0,   -2,     2],
[0,  0, 1,  -1,    3,    -2],
[0,  0, 0, 1.0, -2.0,   1.0],
[0,  0, 0,   0,    0, a + 1]])

In [ ]:
Ab[1,:] = Ab[1,:] + Ab[2,:]
Ab

Matrix([
[1, -2, 0,   0,   -2,    2],
[0,  0, 1,   0,  1.0, -1.0],
[0,  0, 0, 1.0, -2.0,  1.0],
[0,  0, 0,   0,    0,    0]])

The particular solution is generated by the **pivot** columns:
$$
  \begin{bmatrix}
  x_1\\ x_2\\ x_3 \\ x_4\\ x_5
  \end{bmatrix}
  =
\begin{bmatrix}
 2\\ 0\\ -1\\ 1\\ 0
 \end{bmatrix}
 $$

 The other solutions are generated by combining the pivot and non pivot columns so as to get the zero vector.



### Example 2.7 (Reduced Row Echelon Form)

In [ ]:
A = np.vstack([[1,3,0,0,3],[0,0,1,0,9],[0,0,0,1,-4]])
A

array([[ 1,  3,  0,  0,  3],
       [ 0,  0,  1,  0,  9],
       [ 0,  0,  0,  1, -4]])


*Look for solutions of Ax = 0 by looking at non-pivot columns*.

1. The 2nd column is 3 times the 1st column.
2. To obtain 0 we subtract the 2nd column from three times the 1st column.
3. The 5th column is our 2nd non-pivot. It can be expressed as 3 times the 1st pivot column,
    9 times the 2nd pivot column, and -4 times the 3rd pivot column.
4. Track the indices of the pivot columns and translate this into:
    1. 3 times the 1st pivot column,
    2. 0 times the 2nd column, (the 1st non-pivot)
    3. 9 times the 3rd column, and (the 2nd pivot column)
    4. -4 times the 4th column  (the 3rd pivot column)
5. Subtract the 5th column to obtain 0.

### Example 2.8 (Minus-1 Trick)

In [ ]:
A1 = A
A1

array([[ 1,  3,  0,  0,  3],
       [ 0,  0,  1,  0,  9],
       [ 0,  0,  0,  1, -4]])

The trick is to have the diagonal have either 1 or -1.

In [ ]:
A1 = np.insert(A1,1,np.array([0,-1,0,0,0]),0)
A1 = np.insert(A1,4,np.array([0,0,0,0,-1]),0)
A1

array([[ 1,  3,  0,  0,  3],
       [ 0, -1,  0,  0,  0],
       [ 0,  0,  1,  0,  9],
       [ 0,  0,  0,  1, -4],
       [ 0,  0,  0,  0, -1]])

Which gives us the solution from Example 2.7 above in columns 2 and 5.

### Example 2.9 (Calculating an Inverse Matrix by Gaussian Elimination)

In [ ]:
A = np.vstack([[1,0,2,0],[1,1,0,0],[1,2,0,1],[1,1,1,1]])
aug = np.eye(np.shape(A)[0])
A
aug

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
Aaug = np.hstack([A,aug])
Aaug = sym.Matrix(Aaug)
Aaug

Matrix([
[1.0,   0, 2.0,   0, 1.0,   0,   0,   0],
[1.0, 1.0,   0,   0,   0, 1.0,   0,   0],
[1.0, 2.0,   0, 1.0,   0,   0, 1.0,   0],
[1.0, 1.0, 1.0, 1.0,   0,   0,   0, 1.0]])